INSERT INTO CURRENCYEXCHANGE(ID,EXCHANGEFROM,CONVERSIONTO,CONVERSIONMULTIPLE,PORT) VALUES(1001,"USD","INR",60,"9090");
INSERT INTO CURRENCYEXCHANGE(ID,EXCHANGEFROM,CONVERSIONTO,CONVERSIONMULTIPLE,PORT) VALUES(1002,"EUR","INR",75,"9090");
INSERT INTO CURRENCYEXCHANGE(ID,EXCHANGEFROM,CONVERSIONTO,CONVERSIONMULTIPLE,PORT) VALUES(1003,"AUD","INR",25,"9090");